# 以前の内容は一旦消して、こちらに差し替えてください

[tool.ruff]
# LinterとFormatterの両方の設定をここに書きます
line-length = 127

# (オプション) もしフォーマッタだけを有効にしたい場合は以下も追加
# select = []

# (オプション) もし特定のルールを有効にしたい場合はselectに書く
# 例: select = ["E", "F", "W", "I"]