name: Pytest CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # v3からv4に更新
      - name: Setup Python
        uses: actions/setup-python@v5  # v4からv5に更新
        with:
          python-version: '3.11'  # 具体的なバージョンを指定
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.3.0 schedule==1.2.2 pygame==2.6.1 pytest
          # pip install -r requirements.txt の代わりに直接指定
      - name: Run tests
        run: python -m pytest -v  # 詳細出力オプションを追加